{% set version = "0.0.14" %}

package:
  name: particula
  version: {{ version }}

source:
  url: https://github.com/uncscode/particula/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 25c3792603c31832907f4a80277eba155a5b88fbd36c9d603d5ed18c358846f0
  patches:
    - patches/371.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.9
    - numpy
    - pint
    - scipy
    - hypersolver ==0.0.8
    - pandas
    - netCDF4
    - shapely
    - PyMieScatt
    - tqdm
    - pytz
    - matplotlib-base

test:
  requires:
    - pytest
    - pip
  source_files:
    - particula
  commands:
    - pip check
    - python -c "import particula; print(particula.__version__)"
    - pytest

about:
  home: https://uncscode.github.io/particula
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a simple, fast, and powerful particle simulator
  description: |
    Particula is a simple, fast, and powerful particle simulator, or at least two of the three, we hope. 
    It is a simple particle system that is designed to be easy to use and easy to extend. 
    The goal is to have a robust aerosol (gas phase and particle phase) simulation system 
    that can be used to answer scientific questions that arise for experiments and research discussions.
  dev_url: https://github.com/uncscode/particula
  doc_url: https://uncscode.github.io/particula/

extra:
  recipe-maintainers:
    - gorkowski
    - ngam
