{% set version = "0.2.1" %}

package:
  name: particula
  version: {{ version }}

source:
  url: https://github.com/uncscode/particula/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 154afe57ec0428175f004952043e97134f6e1ec2c900ba2a53ae8906c57d54fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2,<4
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - scipy >=1.12

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pip
  source_files:
    - particula
  commands:
    - pip check
    - python -c "import particula; print(particula.__version__)"
    - pytest -W error

about:
  home: https://uncscode.github.io/particula
  license: MIT
  license_family: MIT
  license_file: license
  summary: a simple, fast, and powerful particle simulator
  description: |
    Particula is a Python-based aerosol particle simulator. Its goal is to
    provide a robust aerosol simulation (including both gas and particle phases)
    that can be used to answer scientific questions arising from experiments and research endeavors.
  dev_url: https://github.com/uncscode/particula
  doc_url: https://uncscode.github.io/particula/

extra:
  recipe-maintainers:
    - gorkowski
    - ngam
    - mahf708
