{% set version = "0.1.0" %}

package:
  name: particula
  version: {{ version }}

source:
  url: https://github.com/uncscode/particula/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dd25e371c8906d905c3d8ef71ab5655265f5eacf66f1747110cb175978aeae43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.9,<3.13
    - numpy
    - pint
    - scipy
    - hypersolver ==0.0.8
    - pytz

test:
  requires:
    - pytest
    - pip
  source_files:
    - particula
  commands:
    - pip check
    - python -c "import particula; print(particula.__version__)"
    - pytest

about:
  home: https://uncscode.github.io/particula
  license: MIT
  license_family: MIT
  license_file: license
  summary: a simple, fast, and powerful particle simulator
  description: |
    Particula is a simple, fast, and powerful particle simulator, or at least two of the three, we hope. 
    It is a simple particle system that is designed to be easy to use and easy to extend. 
    The goal is to have a robust aerosol (gas phase and particle phase) simulation system 
    that can be used to answer scientific questions that arise for experiments and research discussions.
  dev_url: https://github.com/uncscode/particula
  doc_url: https://uncscode.github.io/particula/

extra:
  recipe-maintainers:
    - gorkowski
    - ngam
    - mahf708
